CREATE TABLE ATTACH(
                        ID            NUMBER PRIMARY KEY ,
                    PERSON_ID         NUMBER PRIMARY KEY,
                        LICENSE_ID    NUMBER PRIMARY KEY
);

CREATE SEQUENCE ATTACH_SEQ START WITH 1 INCREMENT BY 1;