create table Product
(
    ID         NUMBER,
    NAME       NVARCHAR2(30),
    BRAND      NVARCHAR2(30),
    BUY_PRICE  NUMBER,
    SELL_PRICE NUMBER

);
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;