CREATE TABLE SIM_CARD(
   ID             NUMBER PRIMARY KEY,
   SIM_NUMBER     NVARCHAR2(20),
   PUK_NUMBER     NVARCHAR2(20),
   OPERATOR       NVARCHAR2(20)
);

CREATE SEQUENCE SIM_CARD_SEQ START WITH 1 INCREMENT BY 1;