CREATE TABLE TRIP
(
    ID           NUMBER PRIMARY KEY,
    DESTINATION  NVARCHAR2(50),
    DESCRIPTION  NVARCHAR2(100),
    TAGS         NVARCHAR2(20)
);

CREATE SEQUENCE TRIP_SEQ START WITH 1 INCREMENT BY 1;